### ISSUE TITLE
Demo not working.

### ISSUE THREAD

**Issue by tomgreenhill** [ireade/boilerplate-service-worker#1]
There seems to be a whole host of errors in the console of the demo. :\

**Comment by ireade** [comment]
Hi @maketimetodesign , can you please send a screenshot of the errors you're seeing? Also, make sure you're visiting the HTTPS version of the demo (https://ireade.github.io/boilerplate-service-worker/src/)

Thanks

**Comment by tomgreenhill** [comment]
Hey @ireade, forgive me, not sure why I said 'whole host of errors', it was but one 404! I've been working on something else and must've been thinking about that...sorry! 

<img width="1920" alt="screen shot 2016-05-10 at 11 40 53" src="https://cloud.githubusercontent.com/assets/1922302/15143931/2f525e64-16a4-11e6-96cc-46e4df681cb7.png">

**Comment by ireade** [comment]
Ah okay phew! I've seen the problem, it's actually to do with the APIs I was using, made a fix for now.

**Comment by tomgreenhill** [comment]
Yeah sorry for the false alert @ireade! Awesome, will take another look!

**Comment by tomgreenhill** [comment]
AND of COURSE, thank you for the demo! Sorry, my brain isn't with me today!

**Comment by ireade** [comment]
No problem :) @maketimetodesign
